language: ruby
rvm:
- 2.3.1

cache:
  bundler: true
  directories:
    - vendor/bundle

before_install:
  - gem install -v 2.0.1 bundler

install:
- bundle install

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: master